### PR TITLE
Upgrade Matomo to v4.15.1

### PR DESCRIPTION
**Pull request by vab**
### What does this PR do?

This PR updates the Dockerfile to Matomo v4.15.1.

### Helpful background context

I'm merging this change into main so that I can do a stage deploy. After testing is complete in stage, I will coordinate with the stake holders and tag it for production.

### How can a reviewer manually see the effects of these changes?

Matomo v4.15.1 is currently deployed in dev1.

### Includes new or updated dependencies?

YES (A new version of the official Matomo Docker image as specified by the repository's Dockerfile.)

### What are the relevant tickets?

https://mitlibraries.atlassian.net/browse/INFRA-391

### Developer

- [X] All new ENV is documented in README (or there is none)
- [X] Stakeholder approval has been confirmed (or is not needed)

### Code Reviewer

- [ ] The commit message is clear and follows our guidelines
      (not just this pull request message)
- [ ] There are appropriate tests covering any new functionality
- [ ] The documentation has been updated or is unnecessary
- [ ] The changes have been verified
- [ ] New dependencies are appropriate or there were no changes

### CODE REVIEW

**Review by tim-rix — COMMENTED** [review]
Shouldn't this PR go into `stage` from `dev`?

**Comment by vab** [comment]
> Shouldn't this PR go into `stage` from `dev`?

Yes. But, this is an older repo that predates our standards. There currently is no stage branch. (That's why my commit is odd with more than one. I had expected there was as well. I didn't realize there wasn't a stage until I tried to make a PR to it.)

I was going to talk with Christopher about what he wants to do with this repo. If he's OK with it, I'll bring it in line with our best practices. But, I also noticed the PR template and some other things were different (and a non-infra dev is one of the contributors). So, perhaps it's based off of EngX's standards rather than Infra's and it should stay that way?

Anyway, he and I already talked about some other changes to modernize the Matomo code and clear some technical debt. He told me to just get this upgrade done first and then work on that. He didn't want to mix multiple changes in the deploy cycle and the upgrade was customer requested (in the linked JIRA ticket).

**Review by tim-rix — APPROVED** [review]
Forgot there was no stage on this repo...lgtrm

**Comment by cabutlermit** [comment]
This repo is good the way it is. The app repos are GitHub-flow (just one `main` branch and then feature branches). The infrastructure repos are simplified git-flow (multiple long-running branches).

Alex's approach (PR from feature branch to `main` is correct to push the updated app to Stage-Workflows) is correct. And, then once the testing in stage is done, tag a release on `main` to copy the updated container to Prod-Workloads.

**Pull request merged**
