### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by tim-rix**
### What does this PR do?

Updates Matomo to 5.0.1 (latest)

### How can a reviewer manually see the effects of these changes?

Login to Matomo on Dev1 [https://matomo-ecs-dev.dev1.mitlibrary.net/](https://matomo-ecs-dev.dev1.mitlibrary.net/)

### Includes new or updated dependencies?

YES - Requires a database upgrade

### What are the relevant tickets?

[INFRA-413](https://mitlibraries.atlassian.net/browse/INFRA-413)

### Developer

- [X] All new ENV is documented in README (or there is none)
- [X] Stakeholder approval has been confirmed (or is not needed)

### Code Reviewer

- [x] The commit message is clear and follows our guidelines
      (not just this pull request message)
- [x] There are appropriate tests covering any new functionality
- [x] The documentation has been updated or is unnecessary
- [x] The changes have been verified
- [x] New dependencies are appropriate or there were no changes

[INFRA-413]: https://mitlibraries.atlassian.net/browse/INFRA-413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by vab — DISMISSED** [review]
lgtm. Remember use use the tf repo (mitlib-tf-workloads-matomo) to do the db upgrade (rds.tf) and update the README.md in that repo as well (it directly mentions the mariadb version)

**Comment by vab** [comment]
I'm not sure why it's seeing conflicts. Maybe the way you switched between branches with git (or the new shared workflows). The only conflict, of course, is the matomo version. So, I'd just resolve that in the github webui editor and merge.

**Comment by tim-rix** [comment]
The conflict has been resolved so this needs a new review.  

It looks like the last PR was for Dev-->Dev, which could have triggered the conflict.  Also, looking at the TF repo, rds-mariadb.tf looks like it's for upgrading the MariaDB engine version.  We're still using version 10.5.

**Review by vab — APPROVED** [review]
lgtm.

Gotcha on the db upgrade. I thought you meant a RDS version not just a schema. We should probably talk to Christopher about clearing that up in our workflow templates.

**Pull request merged**
